name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests-php:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          ini-values: upload_max_filesize=10M

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP Dependencies
        run: composer install --no-scripts --prefer-dist --no-progress

      - name: Execute PHP tests (Unit and Feature tests) via Nette Tester
        run: vendor/bin/phpunit
